### ISSUE TITLE
Malloc-related Issue in Benchmark.py

### ISSUE THREAD

**Issue by ian-a-mitchell** [TheoremEngine/Viridicle#1]
After having to reset my MacPorts install today for unrelated reasons, I decided to rerun Viridicle's tests and examples to check that it would work properly on my current install. Running benchmarks.py, however, led to an immediate series of crashes related to malloc (more specifically, to "incorrect checksum for freed object"), which only terminated when I manually killed the process with ^C. I have attached the console output below and a list of installed ports in case the latter is relevant.

[consoleOutput.txt](https://github.com/TheoremEngine/Viridicle/files/7331745/consoleOutput.txt)
[portList.txt](https://github.com/TheoremEngine/Viridicle/files/7331777/portList.txt)

**Comment by Mark-Lowell** [comment]
When you reset your MacPorts, did the version of Python change? If it did, did you try reinstalling Viridicle after the change?

Also, did this happen only with benchmark.py, or also with the unit tests?

**Comment by ian-a-mitchell** [comment]
It shouldn’t have changed, because I was using the py39 package both times and update daily. In any case, I did reinstall Viridicle afterwards.

This only happened with benchmark.pay; the unit tests ran with no issues, and benchmark_python didn’t finish after several hours of running, so I was unable to evaluate it (this may have been because I was doing other computationally-intensive activities, however)

**Comment by Mark-Lowell** [comment]
Could you try adjusting NUM_WORKERS to 1 and NUM_EXPERIMENTS to 16 in benchmark, and then see if it still errors out? Since the test script runs successfully, I suspect this is related to the benchmark script assuming you have more CPU cores than you actually do. It's expecting to be run on a fairly large AWS EC2 instance.

**Comment by ian-a-mitchell** [comment]
While that reduced the number of errors (and eliminated the need for me to manually kill the process), it didn't eliminate them; I've attached the new console output below, but it appeared to be substantially similar to the old output.

[newConsoleOutput.txt](https://github.com/TheoremEngine/Viridicle/files/7357500/newConsoleOutput.txt)

**Comment by Mark-Lowell** [comment]
I've been able to replicate the problem on my Mac laptop. It does appear to be specific to Mac, as it does not occur on Ubuntu (I don't have a Windows machine to test). The problem still occurs if run_may_and_leonard.py is run with num_workers=1 and num_experiments=1. It appears to be random; I can run the same code, get an error, then run it again and not get an error (which is making debugging a real treat). It occurs rarely with num_experiments=1 - I initially thought that prevented the issue entirely - but it does occur maybe 10% of the time. It almost always occurs with num_experiments=2. It still occurs even if I set compiler optimization to O0 and stick Py_RETURN_NONE at the top of run_system, before any variable declarations... So whatever is going wrong has something to do with the integration of the C code into Python, not with the C code itself...

**Comment by Mark-Lowell** [comment]
Could you pull the newest version and check if the problem is still occurring? It works now on my laptop.

**Comment by ian-a-mitchell** [comment]
With the latest version, this issue is no longer occurring. Benchmark.py is running smoothly on my computer.

**Comment by Mark-Lowell** [comment]
Thanks!
